apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube-chart.fullname" . }}
  labels:
    app: {{ include "sonarqube-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sonarqube-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sonarqube-chart.name" . }}
    spec:
      containers:
        - name: sonarqube
          image: "{{ .Values.sonarqube.image.repository }}:{{ .Values.sonarqube.image.tag }}"
          imagePullPolicy: {{ .Values.sonarqube.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.sonarqube.service.port }}
          env:
            - name: SONAR_JDBC_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
            - name: SONAR_JDBC_USERNAME
              value: {{ .Values.postgresql.auth.username }}
            - name: SONAR_JDBC_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
