apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube-chart.fullname" . }}
spec:
  type: {{ .Values.sonarqube.service.type }}
  ports:
    - port: {{ .Values.sonarqube.service.port }}
      targetPort: {{ .Values.sonarqube.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "sonarqube-chart.name" . }}
